/**
 * @addtogroup examplesdcpsatcisocpp
 */
/** @{*/
/** @file */

/*                CycloneDDS isoC++ example 
 *
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 *
 */

module ATCDataModule
{

  struct Position {
            short x; // latitude 
            short y; // longitude 
            short z; // altitude

	};


   struct Flight
   {
      /** Flight Call ID */
      long ID; //@Key

      Position pos;
      // float Speed; 
      /**  Current Region we are flying into*/
      string CurrentRegion; 
   };
   #pragma keylist Flight ID
};

/** @}*/
